name: Biplob Dhaka Court 
description: Biplob Adalat - Court location finder and legal AI assistant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  google_generative_ai: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # ছবিগুলোর পাথ অ্যাপে রেজিস্টার করা হলো
  assets:
    - assets/images/profile.jpg
    - assets/images/splash.jpg
    - assets/images/app_icon.png
    
