name: court_finder
description: A premier app for finding court locations and legal AI assistance.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  google_generative_ai: ^0.2.2 # Gemini AI integration

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
